version: '3.9'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    container_name: database
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 5s
      retries: 20

  server:
    build: ./Server
    container_name: node_server
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: test_db
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    stdin_open: true
    tty: true

  client:
    build: ./Client
    container_name: react_client
    ports:
      - "3000:3000"

volumes:
  db:
    driver: local
